name: Deploy to Firebase Functions

on:
  push:
    branches:
      - main
    paths:
      - "functions/**"
      - "firebase.json"

concurrency:
  group: deploy-functions

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: "functions/.nvmrc"
          cache: "npm"
          cache-dependency-path: functions/package-lock.json

      - run: npm ci
        working-directory: functions

      - name: Deploy to Firebase
        run: npm run deploy
        working-directory: functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
