name: Deploy to Firebase Functions

on:
  push:
    branches:
      - main
    paths:
      - "functions/**"
      - "firebase.json"

concurrency:
  group: deploy-functions

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          package_json_file: functions/package.json

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: "functions/.nvmrc"
          cache: "pnpm"
          cache-dependency-path: functions/pnpm-lock.yaml

      - run: pnpm install --frozen-lockfile
        working-directory: functions

      - name: Test
        run: pnpm test
        working-directory: functions

      - name: Authenticate
        uses: google-github-actions/auth@v3
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_AVATARS_333CB }}

      - name: Deploy to Firebase
        run: pnpm run deploy
        working-directory: functions
